name: quantoposso
description: App semplice per controllo spese (giornaliere + fisse) con obiettivi e promemoria.
publish_to: "none"
version: 1.0.0+535

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^1.1.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icona.png"

  adaptive_icon_foreground: "assets/icon/logo_fg.png"
  adaptive_icon_background: "#2563EB"