name: quantoposso
description: App semplice per controllo spese (giornaliere + fisse) con obiettivi e promemoria.
publish_to: "none"
version: 1.0.0+805

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.1.13  

  url_launcher: ^6.3.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.11.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  printing: ^5.14.2
  fl_chart: ^1.1.1
  path_provider: ^2.1.5
  share_plus: ^10.0.2
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/iconanuova.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/iconanuova.png"  